/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-61e2a7f1",
        "v-0f83f151"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-61e2a7f1",
        "v-0f83f151"
      ]
    }
  },
  "categories": {
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-61e2a7f1"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-0f83f151"
      ]
    }
  },
  "timeline": {}
}